name: build

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: microsoft/setup-msbuild@v1
    - run: MSBuild.exe $Env:GITHUB_WORKSPACE\src\KemonoFriendsCMC.Mods.ShowUsingMod\KemonoFriendsCMC.Mods.ShowUsingMod.csproj -p:Configuration=Release
      timeout-minutes: 5
